### ISSUE TITLE
error fast-unique-numbers@8.0.2: The engine "node" is incompatible with this module.

### ISSUE THREAD

**Issue by dolovitseasy** [chrisguttandin/fast-unique-numbers#480]
As it turned out, a lot of good packages use this repository in their dependencies. But when installing any of this package, an error is generated that THIS package requires version 16, although the rest do not. It turns out that all projects on the Internet should be updated because of you to version 16? It is very difficult in some cases, somewhere it is completely impossible. Such a minor package causes all packages to throw an error - fix it! For example, I'm only on version 14.
Is it difficult to calculate quickly unique numbers on the 14th version of nodes?

**Comment by sliwei** [comment]
I found compatibility node@14 The last version of is 7.0.2

**Comment by chrisguttandin** [comment]
I think this is a similar problem as the one described in chrisguttandin/worker-timers#435. Unfortunately I don't know of a way to mark a package as frontend only to convince the package manager to ignore the `engines` property.

The error message looks like it's coming from yarn. At least v1 could be configured to install the package anyway by using the `--ignore-engines` flag.
